/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "forward.h"

void
fileforward_1(char *host, char *tmpfilename)
{
	CLIENT *clnt;
	int  *result_1;
	file  filefwd_1_arg;
	FILE *ofile;
	int len = 0;

#ifndef	DEBUG
	clnt = clnt_create (host, FILEFORWARD, FILEFORWARD_1, "tcp");
	if (clnt == NULL) {
		clnt_pcreateerror (host);
		exit (1);
	}
#endif	/* DEBUG */

	ofile = fopen(tmpfilename, "rb");

	if(ofile == NULL) {
		printf("File not found.\n");
		exit(1);
	}

	printf("Sending file %s.\n", tmpfilename);

	strcpy(filefwd_1_arg.filename, tmpfilename);

	while(1) {
		filefwd_1_arg.nbytes = fread(filefwd_1_arg.content, 1, MAXLEN, ofile);
		len += filefwd_1_arg.nbytes;
		int tmpcsum = 0;
		for(int i = 0; i < filefwd_1_arg.nbytes; i++)
		{
			tmpcsum = tmpcsum ^ (int)(filefwd_1_arg.content[i]);
		}
		filefwd_1_arg.checksum = tmpcsum;
		printf("\n%d bytes of %s sent to server with checksum %d",len,filefwd_1_arg.filename,filefwd_1_arg.checksum);

		result_1 = filefwd_1(&filefwd_1_arg, clnt);

		if (result_1 == (int *) NULL) {
			clnt_perror (clnt, "call failed");
		}
		
		if(*result_1 == 1) {
			printf("\nFile corrupted. Send Again.\n");
			break;
		}

		if(filefwd_1_arg.nbytes < MAXLEN) {
			printf("\nUpload finished.\n");
			break;
		}

	}

	
#ifndef	DEBUG
	clnt_destroy (clnt);
#endif	 /* DEBUG */
}


int
main (int argc, char *argv[])
{
	char *host;
	char *tmpfilename;

	if (argc < 3) {
		printf ("usage: %s server_host\n", argv[0]);
		exit (1);
	}
	host = argv[1];
	tmpfilename = argv[2];

	fileforward_1 (host, tmpfilename);
exit (0);
}
