/*
 * This is sample code generated by rpcgen.
 * These are only templates and you can use them
 * as a guideline for developing your own functions.
 */

#include "forward.h"

char opened_file[MAXLEN];
FILE *ofile;
int len = 0;

int *
filefwd_1_svc(file *argp, struct svc_req *rqstp)
{
	static int  result;
	static char tempName[MAXLEN];
	int chsum;
	static int cnt = 0;
	cnt++;
	/*
	 * insert server code here
	 */

	len += argp->nbytes;
	
	if (strcmp(opened_file, "") == 0 && ofile == NULL) {
		printf("Receiving new file %s now.\n", argp->filename);

		strcpy(opened_file, argp->filename);
		ofile = fopen(argp->filename, "ab+");
	}
	if (strcmp(opened_file, argp->filename) == 0) {
		printf("\n %d bytes of file %s were received with checksum %d", len, argp->filename, argp->checksum);
		fflush(stdout);
		chsum = argp->checksum;
		for(int i = 0; i < argp->nbytes; i++)
		{
			chsum = chsum ^ (int)(argp->content[i]);
		}
		// Snippet to check error
		//if(cnt == 2) chsum = 1;
		if(chsum == 0) 
		{
			printf("\nChecksum is 0 so msg received properly!!");
			fwrite(argp->content, 1, argp->nbytes, ofile);
		}
		else
		{ 
			printf("\nAlert: Checksum is not 0, ie %d, file corrupted. Ask sender to send file again.\n",chsum); 
			len = 0;
			fclose(ofile);
			ofile = NULL;
			strcpy(opened_file, "");
			result = 1;			
			return &result;
		}

		if (argp->nbytes < MAXLEN) {
			printf("\nFinished checkum also got receiving %s.\n", argp->filename);
			len = 0;
			fclose(ofile);
			ofile = NULL;
			strcpy(opened_file, "");
		}
	}
	return &result;
}
